"""Compositing and visual effects tools including character pinning, PiP, and export rendering."""

from __future__ import annotations

from typing import Any

from app.models.schemas import (
    MaskedPiPInput,
    MaskedPiPOutput,
    PinOverlayInput,
    PinOverlayOutput,
    RenderExportInput,
    RenderExportOutput,
    ToolErrorResponse,
)
from app.observability.intent_outcome import IntentOutcomeAuditLogger
from app.observability.tracing import trace_span
from app.tools.timeline_tools import default_engine


def pin_character_overlay_to_track(
    target_track_id: str,
    overlay_asset_id: str,
    tracking_id: str,
    mask_id: str | None = None,
    blend_mode: str = "normal",
    opacity: float = 1.0,
) -> dict[str, Any]:
    """Pins a graphic overlay or character cutout onto a tracked character trajectory.

    Attaches a graphics layer or character cutout onto an upper video track (e.g. V2 or V3),
    driving its frame-by-frame 2D transform from a previously calculated motion tracking ID.
    Can also apply a rotoscope mask to cleanly blend the overlay.

    Args:
        target_track_id: Upper track identifier to place the overlay on (e.g. 'V2', 'V3').
        overlay_asset_id: Identifier of the graphic or video asset to pin (e.g. 'hat_prop_01').
        tracking_id: Identifier of the motion tracking keyframes generated by
            track_character_motion_keyframes.
        mask_id: Optional rotoscope mask identifier to crop the overlay.
        blend_mode: Compositing blend mode ('normal', 'multiply', 'screen', 'add').
        opacity: Layer transparency factor from 0.0 to 1.0.

    Returns:
        A dictionary conforming to PinOverlayOutput confirming composite clip creation,
        keyframes attached, and applied blend mode.
        If validation fails, returns a structured ToolErrorResponse.
    """
    with trace_span("tool.pin_character_overlay_to_track", {
        "target_track_id": target_track_id,
        "overlay_asset_id": overlay_asset_id,
        "tracking_id": tracking_id,
    }):
        start_t = IntentOutcomeAuditLogger.log_intent(
            correlation_id=f"pin_{overlay_asset_id}",
            agent_name="VFXCompositorAgent",
            tool_name="pin_character_overlay_to_track",
            arguments={
                "target_track_id": target_track_id,
                "overlay_asset_id": overlay_asset_id,
                "tracking_id": tracking_id,
                "mask_id": mask_id,
                "blend_mode": blend_mode,
                "opacity": opacity,
            },
            intent_summary=f"Pin overlay asset '{overlay_asset_id}' to tracking ID '{tracking_id}' on track '{target_track_id}'.",
        )
        try:
            validated = PinOverlayInput(
                target_track_id=target_track_id,
                overlay_asset_id=overlay_asset_id,
                tracking_id=tracking_id,
                mask_id=mask_id,
                blend_mode=blend_mode,
                opacity=opacity,
            )
            result = default_engine.pin_character_overlay_to_track(
                target_track_id=validated.target_track_id,
                overlay_asset_id=validated.overlay_asset_id,
                tracking_id=validated.tracking_id,
                mask_id=validated.mask_id,
                blend_mode=validated.blend_mode,
                opacity=validated.opacity,
            )
            output = PinOverlayOutput(**result).model_dump()
            IntentOutcomeAuditLogger.log_outcome(
                correlation_id=f"pin_{overlay_asset_id}",
                agent_name="VFXCompositorAgent",
                tool_name="pin_character_overlay_to_track",
                start_time=start_t,
                status="SUCCESS",
                result=output,
            )
            return output
        except KeyError as err:
            error_resp = ToolErrorResponse(
                error_code="TRACKING_OR_TRACK_MISSING",
                message=str(err),
                recovery_instructions="Run track_character_motion_keyframes() to generate a valid tracking_id before calling pin_character_overlay_to_track().",
                suggested_tool="track_character_motion_keyframes",
                suggested_arguments={"target_label": "character_face"},
            ).model_dump()
            return error_resp
        except Exception as exc:
            error_resp = ToolErrorResponse(
                error_code="PIN_OVERLAY_FAILED",
                message=f"Failed to pin overlay to track: {exc!s}",
                recovery_instructions="Check that target_track_id exists and tracking_id is valid.",
                suggested_tool="get_timeline_state",
                suggested_arguments=None,
            ).model_dump()
            return error_resp


def create_masked_picture_in_picture(
    base_track_id: str,
    pip_track_id: str,
    pip_clip_id: str,
    position: str = "top-right",
    normalized_x: float = 0.75,
    normalized_y: float = 0.75,
    scale: float = 0.28,
    mask_shape: str = "rounded_rect",
    border_width: int = 4,
    border_color: str = "#FFFFFF",
) -> dict[str, Any]:
    """Creates a Picture-in-Picture (PiP) composite on an upper track with a custom mask shape.

    Composites a secondary video clip (e.g. speaker facecam or reaction clip) over the primary
    background video track. Automatically scales the clip, applies a shape mask (circle, rounded_rect,
    silhouette), positions it on the timeline coordinates, and adds an optional border stroke.

    Args:
        base_track_id: Lower track ID providing the full-screen background video (e.g. 'V1').
        pip_track_id: Upper track ID holding the PiP clip (must have higher index than base track, e.g. 'V2' or 'V3').
        pip_clip_id: Unique clip ID on the upper track to turn into a PiP window (e.g. 'clip_broll_001').
        position: Location preset ('top-right', 'top-left', 'bottom-right', 'bottom-left', 'center', 'custom').
        normalized_x: Normalized horizontal coordinate of PiP center from 0.0 (left) to 1.0 (right).
        normalized_y: Normalized vertical coordinate of PiP center from 0.0 (bottom) to 1.0 (top).
        scale: Scale factor relative to canvas size (e.g. 0.28 = 28% of canvas width).
        mask_shape: Mask geometry shape ('rounded_rect', 'circle', 'silhouette', 'ellipse').
        border_width: Frame border stroke width in pixels (0 to 20).
        border_color: Frame border color as a HEX string (e.g. '#FFFFFF').

    Returns:
        A dictionary conforming to MaskedPiPOutput detailing the composite ID,
        coordinates, mask shape, and border configuration.
        If validation fails (such as invalid track layering), returns a structured ToolErrorResponse.
    """
    with trace_span("tool.create_masked_picture_in_picture", {
        "base_track_id": base_track_id,
        "pip_track_id": pip_track_id,
        "pip_clip_id": pip_clip_id,
        "position": position,
    }):
        start_t = IntentOutcomeAuditLogger.log_intent(
            correlation_id=f"pip_{pip_clip_id}",
            agent_name="VFXCompositorAgent",
            tool_name="create_masked_picture_in_picture",
            arguments={
                "base_track_id": base_track_id,
                "pip_track_id": pip_track_id,
                "pip_clip_id": pip_clip_id,
                "position": position,
                "normalized_x": normalized_x,
                "normalized_y": normalized_y,
                "scale": scale,
                "mask_shape": mask_shape,
                "border_width": border_width,
                "border_color": border_color,
            },
            intent_summary=f"Create {mask_shape} PiP of '{pip_clip_id}' on track '{pip_track_id}' over '{base_track_id}' at {position}.",
        )
        try:
            validated = MaskedPiPInput(
                base_track_id=base_track_id,
                pip_track_id=pip_track_id,
                pip_clip_id=pip_clip_id,
                position=position,  # type: ignore
                normalized_x=normalized_x,
                normalized_y=normalized_y,
                scale=scale,
                mask_shape=mask_shape,  # type: ignore
                border_width=border_width,
                border_color=border_color,
            )
            result = default_engine.create_masked_picture_in_picture(
                base_track_id=validated.base_track_id,
                pip_track_id=validated.pip_track_id,
                pip_clip_id=validated.pip_clip_id,
                position=validated.position.value,
                normalized_x=validated.normalized_x,
                normalized_y=validated.normalized_y,
                scale=validated.scale,
                mask_shape=validated.mask_shape.value,
                border_width=validated.border_width,
                border_color=validated.border_color,
            )
            output = MaskedPiPOutput(**result).model_dump()
            IntentOutcomeAuditLogger.log_outcome(
                correlation_id=f"pip_{pip_clip_id}",
                agent_name="VFXCompositorAgent",
                tool_name="create_masked_picture_in_picture",
                start_time=start_t,
                status="SUCCESS",
                result=output,
            )
            return output
        except ValueError as val_err:
            error_resp = ToolErrorResponse(
                error_code="INVALID_LAYER_HIERARCHY",
                message=str(val_err),
                recovery_instructions="Ensure the pip_track_id sits vertically above base_track_id (e.g. pip_track_id='V2' and base_track_id='V1').",
                suggested_tool="create_masked_picture_in_picture",
                suggested_arguments={"base_track_id": "V1", "pip_track_id": "V2"},
            ).model_dump()
            return error_resp
        except KeyError as key_err:
            error_resp = ToolErrorResponse(
                error_code="TRACK_OR_CLIP_NOT_FOUND",
                message=str(key_err),
                recovery_instructions="Invoke get_timeline_state() to discover valid tracks and clips before configuring Picture-in-Picture.",
                suggested_tool="get_timeline_state",
                suggested_arguments=None,
            ).model_dump()
            return error_resp
        except Exception as exc:
            error_resp = ToolErrorResponse(
                error_code="PIP_CREATION_FAILED",
                message=f"Picture-in-Picture composition failed: {exc!s}",
                recovery_instructions="Check normalized coordinates (0.0 to 1.0) and retry.",
                suggested_tool="create_masked_picture_in_picture",
                suggested_arguments=None,
            ).model_dump()
            return error_resp


def render_mock_composite_export(
    output_format: str = "mp4",
    resolution: str = "1920x1080",
    fps: float = 24.0,
    render_preset: str = "ProRes_422",
    approval_token: str | None = None,
) -> dict[str, Any]:
    """Simulates exporting and rendering the final edited multi-track composite timeline.

    Renders all composited tracks, PiP layouts, masks, and cuts into a final export video file.
    NOTE: This is a high-stakes action governed by Human-in-the-Loop (HITL) confirmation.

    Args:
        output_format: Target media container format ('mp4', 'mov', 'webm').
        resolution: Output frame dimensions ('1920x1080', '3840x2160', '1080x1920').
        fps: Render frame rate (e.g. 24.0, 30.0, 60.0).
        render_preset: Encoding profile ('ProRes_422', 'H264_High', 'YouTube_1080p').
        approval_token: Optional HITL approval token required to authorize high-stakes export.

    Returns:
        A dictionary conforming to RenderExportOutput detailing the simulated render job ID,
        export file path, rendered clip count, and simulated render time.
    """
    with trace_span("tool.render_mock_composite_export", {
        "output_format": output_format,
        "resolution": resolution,
        "fps": fps,
    }):
        start_t = IntentOutcomeAuditLogger.log_intent(
            correlation_id="render_export_job",
            agent_name="VFXCompositorAgent",
            tool_name="render_mock_composite_export",
            arguments={
                "output_format": output_format,
                "resolution": resolution,
                "fps": fps,
                "render_preset": render_preset,
                "approval_token": approval_token,
            },
            intent_summary=f"Render mock export at {resolution} {fps}fps format {output_format}.",
        )
        try:
            validated = RenderExportInput(
                output_format=output_format,  # type: ignore
                resolution=resolution,
                fps=fps,
                render_preset=render_preset,
                approval_token=approval_token,
            )
            result = default_engine.render_mock_composite_export(
                output_format=validated.output_format.value,
                resolution=validated.resolution,
                fps=validated.fps,
                render_preset=validated.render_preset,
            )
            output = RenderExportOutput(**result).model_dump()
            IntentOutcomeAuditLogger.log_outcome(
                correlation_id="render_export_job",
                agent_name="VFXCompositorAgent",
                tool_name="render_mock_composite_export",
                start_time=start_t,
                status="SUCCESS",
                result=output,
            )
            return output
        except Exception as exc:
            error_resp = ToolErrorResponse(
                error_code="RENDER_EXPORT_FAILED",
                message=f"Export render job failed: {exc!s}",
                recovery_instructions="Verify render preset and resolution string before retrying export.",
                suggested_tool="render_mock_composite_export",
                suggested_arguments={"output_format": "mp4", "resolution": "1920x1080"},
            ).model_dump()
            return error_resp
